### ISSUE TITLE
Is it possible to develop a tool that will send DMs with Different Accounts (with Proxies) on a massive scale (10k dms per day)?

### ISSUE THREAD

**Issue by MuhammadShahzeb123** [JaceMason/RedditGrabber#2]
I saw your grabber and I just wanna know if it is possible for you to make a tool like the header mentions. Thanks

**Comment by JaceMason** [comment]
I have never pushed Selenium to the bounds of how fast it could be, so I am not actually sure. It was pretty slow when I was working on this years ago, so I suspect it would be a struggle to send that many messages.

In any case, that sounds like something that would need to be done through Reddit's API. I appreciate your interest though!
